<?php

if( !defined("SITEROOT") ) define( "SITEROOT", DRUPAL_ROOT."/../" );    // because seedbreeze.theme also does this
include_once( SITEROOT."site.php" );
include_once( SITEROOT."drupalmod/lib/d8_seedbreeze.php" );

/* All of the code here could go in drupalmod/lib but it is here instead to remind us that the function entry points here are
 * cached in Drupal 8 and the functions they call are not. You can modify anything in drupalmod/lib without refreshing the Drupal 8 cache
 * but if you add or change a function api here you have to refresh the cache to see the effect.
 */

function seeds_preprocess_page( &$variables ) {
    D8SeedsModule_PreprocessPage( $variables );
}

function seeds_node_view_alter( $build, $node, $display )
{
    D8SeedsModule_NodeViewAlter( $build, $node, $display );
}

function seeds_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
    D8SeedsModule_NodeView( $build, $entity, $display, $view_node );
}

?>
