<?
require_once("/home/154977/domains/seedliving.ca/html/lib/class/captcha.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/class/mas.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/class/tkntbl.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/tmplt.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/aslib.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/mas.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/tkntbl.php");
require_once("/home/154977/domains/seedliving.ca/html/lib/paypalplatform.php");

define("OPENTAG","[SL]");
define("CLOSETAG","[/SL]");
define("MYSQL_SERVER","internal-db.s154977.gridserver.com");
define("MYSQL_LOGIN","db154977_sldb");
define("MYSQL_PASS","s@@dLiv1ngDB");
define("MYSQL_DB","db154977_sldb");
define("SL_COOKIE","sllive");
define("SL_CART","slcart");
define("TEMPLROOT","/home/154977/domains/seedliving.ca/html/templates/");
define("IMAGEROOT","/home/154977/domains/seedliving.ca/html/i/");
define("CAPTCHA","/home/154977/domains/seedliving.ca/html/i/elephant.ttf");
define("CAPTCHA_DIR","/home/154977/domains/seedliving.ca/html/_captcha");
define("COOKIE_DOMAIN","seedliving.ca");
define("SEARCH_TRACKER","st");
?>